import { STOPS } from './src/data/transitData';
import fs from 'fs';

const routesRaw = [
  { number: '3', name: 'Dahighat ⇄ Sealdah', stops: ['Khidderpur', 'Mominpur', 'Hazra', 'Elgin Road', 'Park Street', 'Esplanade', 'Subodh Mallick Square', 'Moulali'] },
  { number: '15', name: 'Ultadanga ⇄ Howrah', stops: ['Ultadanga', 'Khanna', 'Hatibagan', 'Grey St', 'Nimtala Ghat St', 'B.K. Paul Ave', 'Howrah Bridge East', 'Howrah Stn'] },
  { number: '33', name: 'Chetla ⇄ Paikpara', stops: ['Paikpara', 'Shyambazar', 'Khanna', 'Manicktala', 'Sealdah', 'Moulali', 'Padmapukur', 'Darga Rd', 'Bondel Gate', 'Hazra', 'Kalighat', 'Alipur Rd', 'Chetla'] },
  { number: '7A', name: 'Sarsuna ⇄ Howrah', stops: ['Sarsuna', 'Bakultala', 'Chowrasta', 'Manton Xing', 'Behala Tram Depot', 'Taratala Xing', 'Mominpur', 'Khidirpur', 'Casurina Ave', 'Esplanade', 'BBD Bag', 'Howrah Stn'] },
  { number: '11A', name: 'Dum Dum ⇄ Howrah', stops: ['Dum Dum Stn', 'Chiria More', 'Shyambazar', 'Manicktala', 'Bedon Square', 'Howrah Bridge East', 'Barabazar', 'Howrah Stn'] },
  { number: '5-N', name: 'Garia ⇄ Nabanna', stops: ['Garia', 'Ganguli Bagan', 'Baghajatin', 'Jadavpur', 'Dhakuria', 'Golpark', 'D Park', 'R.B. Ave', 'Hazra', 'Elgin', 'Exide', 'PTS', 'Nabanna'] },
  { number: 'AC-2', name: 'Barasat ⇄ Howrah Station', stops: ['Hridaypur', 'Madhyamgram Chowrasta', 'Doltala', 'New Barrackpur B.T. College', 'Michael Nagar', 'Bankra More', 'Birati More', 'Airport Gate No. 1', 'Kaikhali/Haldiram', 'Teghoria', 'Kestopur/Baguihati', 'Bangur/Dum Dum Park', 'Lake Town Xing', 'HUDCO/Ultadanga', 'Kankurgachi', 'Manicktala', 'Girish Park', 'M.G. Road Xing', 'Satyanarayan Park', 'Howrah Bridge East'] },
  { number: 'AC-4', name: 'Parnasree ⇄ Howrah', stops: ['Taratala Xing', 'Mominpur', 'Khiddirpur', 'Hastings', 'PTS', 'Rabindra Sadan', 'Park Street', 'Esplanade', 'BBD Bag', 'Howrah Bridge South'] },
  { number: 'AC-4B', name: 'Joka ⇄ New Town', stops: ['Thakurpukur', 'Cancer Hospital', 'Kabardanga', 'Haridevpur', 'Karunamoyee (Tollygunge)', 'Tollygunge Metro', 'Rashbehari Xing', 'Gariahat', 'Ruby', 'Chingrihata', 'SDF', 'College More', 'Technopolis'] },
  { number: 'AC-9', name: 'Jadavpore ⇄ Karunamoyee', stops: ['Ajoynagar', 'Ruby', 'Chingrihata', 'Beliaghata Con.', 'Central Park'] },
  { number: 'AC-12', name: 'New Town ⇄ Howrah', stops: ['Narkel Bagan', 'Newtown', 'SDF', 'Chingrihata', 'Science City', 'Topsia', 'Exide', 'Esplanade', 'BBD Bag'] },
  { number: 'AC-14', name: 'Baruipur New Terminus ⇄ Karunamoyee', stops: ['Shibanipit', 'Baruipur/Padmapukur', 'Malancha Bazar', 'Harinavi', 'Mission Gate', 'Kamalgazi More', 'Dhalai Bridge', 'Patuli', 'Peerless Hospital', 'Ajay Nagar', 'Ruby', 'Science City', 'Metropolitan', 'KBKC More', 'Central Park'] },
  { number: 'AC-24A', name: 'Kamalgazi ⇄ Howrah Station', stops: ['Dhalai Bridge', 'Patuli', 'Peerless Hospital', 'Ajay Nagar', 'Kalikapur', 'Ruby Hospital', 'Gariahat', 'Rashbehari Xing', 'Hazra Park', 'Rabindrasadan', 'Park Street', 'Esplanade', 'BBD Bag', 'Howrah Bridge East'] },
  { number: 'AC-30', name: 'Lake Town/Jaya Cinema ⇄ Howrah Station', stops: ['HUDCO/Ultadanga', 'Kankurgachi', 'Manicktala', 'Girish Park', 'M.G. Road Xing', 'Barrabazar'] },
  { number: 'AC-31', name: 'Behala Chowrastha ⇄ Jadavpur', stops: ['James Long Sarani', 'Ramkrishna Ashram', 'Motilal Gupta Road', 'Siriti More', 'Karunamoyee (Tollygunge)', 'Lake Gardens'] },
  { number: 'AC-37', name: 'Garia ⇄ Barasat', stops: ['Patuli', 'Rubi Hospital', 'Science City', 'Chingrighata', 'HUDCO', 'V.I.P. Road', 'Airport', 'Doltala', 'Madhyamgram Chowrasta', 'Hridaypur'] },
  { number: 'C-7', name: 'Howrah ⇄ H M Ghosh College', stops: ['Barabazar', 'Dalhousie', 'Esplanade', 'Babughat', 'Princep Ghat', 'Hastings', 'Khidderpore', 'Babubazar', 'BNR More', 'Muduali', 'Kachhi Sarab', 'Garden Reach', 'Ramnagar', 'Fatehpur'] },
  { number: 'C-8', name: 'Barasat ⇄ Joka', stops: ['Dackbanglow More', 'Madhyamgram', 'B.T. College', 'Birati', 'Airport', 'Chinar Park', 'Eco Park', 'Narkelbagan', 'Newtown', 'Sec5', 'Chingrighata', 'Science City', 'Ruby', 'Rashbihari', 'Tollygunge', 'Kabardanga'] },
  { number: 'C-26', name: 'Baruipur ⇄ Howrah', stops: ['Shibanipith', 'Baruipur Hospital', 'Baruipur Station', 'Padmapukur', 'Khasmallick', 'Harinavi', 'Rajpur Bazar', 'Narendrapur', 'Kamalgazi', 'Dhalai Bridge', 'Patuli More', 'Peerless Hospital', 'Hiland Park', 'Ajaynagar', 'EM Bypass', 'Mukundapur', 'Kalikapur', 'Ruby Hospital', 'VIP Bazar', 'Uttar Panchannagram', 'Science City', 'Topsia More', '4no. Bridge', 'Chittaranjan Hospital', 'CIT Road', 'Moulali More', 'Esplanade', 'Dalhousie'] },
  { number: 'C-28', name: 'Barrackpur ⇄ Howrah', stops: ['Titagarh', 'Khardah', 'Sodepur Girja', 'Kamarhati', 'Rathtala More', 'Dunlop More', 'Bonhooghly', 'Tobin Road', 'Sinthee More', 'Chiria More', 'Shyambazar', 'Rajballavpara', 'Sovabazar', 'Girish Park', 'M.G. Road', 'Barabazar'] },
  { number: 'C-37', name: 'Amtala ⇄ Howrah', stops: ['Bishnupur', 'Khariberia', 'Bhasha 14no.', 'Pailan', 'Joka Bridge', 'Thakurpukur', 'Shilpara', 'Sakher Bazar', 'Behala', 'Majherhat', 'Mominpore', 'Ekbalpur', 'Khidderpore', 'Hastings', 'Esplanade', 'Dalhousie'] },
  { number: 'C-42', name: 'Ganganagar ⇄ Howrah', stops: ['BT College', 'Mickelnagar', 'Birati', 'Airport 1 No. Gate', 'Kaikhali', 'Baguiati', 'Kestopur', 'Laketown', 'Ultadanga', 'Kankurgachi', 'Maniktala', 'Rajabazar', 'Sealdha', 'Bank of India', 'Bowbazar', 'Central Avenue', 'BBD Bag/GPO', 'Stand Road'] },
  { number: 'C-43', name: 'Habra ⇄ Garia', stops: ['Ashoknagar', 'Guma', 'Bira', 'Duttapukur', 'Barasat', 'Madhyamgram', 'Airport 1no', 'Chinar Park', 'Eco Park', 'Narkelbagn', 'Newtown', 'Sec5', 'Chingrighata', 'Science City', 'Ruby', 'Ajaynagar', 'Peerless', 'Patuli'] },
  { number: 'D1A', name: 'Barasat ⇄ Tollygunge', stops: ['Dackbanglow More', 'Madhyamgram', 'B.T. College', 'Airport', 'Baguiati', 'Birati', 'Kestopur', 'Laketown', 'Ultadanga', 'EM Byapss', 'Belaghata', 'Chinghreeghata', 'Science City', 'Ruby', 'Gariahgat', 'Rashbihari'] },
  { number: 'E-1', name: 'Jadavpore ⇄ Howrah', stops: ['Jadavpur', 'Dhakuria', 'Golpark', 'Lake Kali Bari', 'RB Avenue', 'Hazra', 'Elgin', 'Rabindra Sadan', 'Park St', 'Esplanade', 'BBD Bag', 'Howrah'] },
  { number: 'EB1', name: 'Nabanna ⇄ Newtown', stops: ['Mandirtala', 'Vidyasagar Setu', 'PTS More', 'Rabindra Sadan', 'Minto Park', 'Beckbagan', 'Park Circus', 'Science City', 'Chingrighata', 'Wipro More', 'College More', 'DLF 1'] },
  { number: 'M-7B', name: 'Shibrampur ⇄ Howrah Station', stops: ['Bakultala', 'Behala Chowrastha', 'Raja Rammohan Roy Rd', 'Karunamoyee (Tollygunge)', 'Tollygunge Metro', 'Rashbehari Xing', 'Exide', 'Park Street', 'Esplanade', 'Mission Row Xing/BBD Bag'] },
  { number: 'S-3W', name: 'Joka ⇄ Eco Space', stops: ['Thakurpukur 3A Stand', 'Thakurpukur Bazar', 'Sakhar Bazar', 'Behala Chorasta', 'Behala Tram Depot', 'Taratala Xing', 'New Alipore', 'Chetla', 'RB Av Xing', 'Gariahat', 'Kasba PS', 'Ruby', 'VIP Bazar', 'Science City', 'Chingrighata', 'Sukanta Nagar', 'Nicco Park', 'SDF', 'College More', 'Techopolis', 'New Town', 'Home Town', 'Narkel Bagan', 'Ecospace', 'Aliah University'] },
  { number: 'S-9', name: 'Jadavpore ⇄ Karunamoyee', stops: ['Sukanta Setu', 'Santoshpur', 'Ruby Hospital', 'VIP Nagar', 'Since City', 'Metropolitan Hou. Est.', 'EM ByPass Connector', 'KBKC More', 'Central Park'] },
  { number: 'S-10', name: 'Airport ⇄ Nabanna', stops: ['Airport 3 no. gate', 'Airport 1 No. gate', 'Central Jail', 'Nager Bazar', 'Dum Dum Stn', 'Chiria More', 'Paikpara Xing', 'Shyam Bazar', 'Grey Street', 'Vivekananda Rd', 'M.G. Road', 'Colutala Street', 'BB Ganguly Xing', 'Esplanade', 'Mayo Rd', 'PTS', 'Toll Plaza', 'Nabanna'] },
  { number: 'S-16', name: 'Thakurpukur ⇄ Salt Lake', stops: ['Thakurpukur 3A Bus Stand', 'Thakurpukur Bazar', 'Silpara', 'Chowrasta', 'Menton', 'Behala Tram Depot', 'Taratala More', 'Mominpore', 'Khiddirpor', 'Water Gate', 'Espl', 'Subodh Mullick Square', 'Moulali', 'Sealdha', 'Rajabazar', 'Manicktala', 'Kankurgachi', 'Hudco', 'PNB', 'C.A. Island', 'Labony', 'Seva Hospital', 'Baisaki Bhavan', 'Karunamoyee'] },
  { number: 'S-17A', name: 'Ariadaha ⇄ Kundghat', stops: ['Dakshineswar', 'Alambazar', 'Bonhooghly', 'Baghajatin Rd', 'Baranagar Bazar', 'Bibir Bazar', 'Cossipur', 'Bag Bazar', 'Sovabazar', 'M.G. Road Jn', 'Colutala St', 'BB Ganguly St', 'BBD Bag', 'Espl', 'Parkstreet', 'Elgin Rd', 'Hazra Rd', 'RB Ave', 'Tollygunge Phari', 'Tollygunge Tram Depot', 'Chandi Ghosh', 'Kudghat'] },
  { number: 'S-12', name: 'New Town ⇄ Howrah', stops: ['SLD Gate', 'Weble House', 'Nicco Park', 'Chinrighata', 'EM Bypass', 'Ranirashmoni Bazar', 'Sealdha', 'Moulali', 'S. Mullick Sq.', 'Esplanade', 'BBD Bag', 'Howrah Bridge East', 'Howrah Stn'] }
];

const stopNameMap = new Map<string, string>();
for (const s of STOPS) {
  stopNameMap.set(s.name.toLowerCase().trim(), s.id);
  stopNameMap.set(s.id.toLowerCase().trim(), s.id);
}

const ALIASES: Record<string, string> = {
  'khidderpur': 'khidderpur',
  'khidirpur': 'khidderpur',
  'khiddirpur': 'khidderpur',
  'khidderpore': 'khidderpur',
  'khiddirpor': 'khidderpur',
  'mominpur': 'mominpur',
  'mominpore': 'mominpur',
  'hazra': 'hazra-road',
  'hazra rd': 'hazra-road',
  'hazra road': 'hazra-road',
  'hazra park': 'hazra-road',
  'elgin': 'elgin-road',
  'elgin rd': 'elgin-road',
  'elgin road': 'elgin-road',
  'park street': 'park-street',
  'park st': 'park-street',
  'parkstreet': 'park-street',
  'esplanade': 'esplanade',
  'espl': 'esplanade',
  'moulali': 'moulali',
  'moulali more': 'moulali',
  'ultadanga': 'ultadanga',
  'hudco': 'ultadanga',
  'hudco/ultadanga': 'ultadanga',
  'khanna': 'khanna',
  'howrah bridge east': 'howrah-bridge',
  'howrah bridge south': 'howrah-bridge',
  'howrah bridge': 'howrah-bridge',
  'howrah stn': 'howrah-station',
  'howrah station': 'howrah-station',
  'howrah': 'howrah-station',
  'shyambazar': 'shyambazar',
  'shyam bazar': 'shyambazar',
  'manicktala': 'maniktala',
  'sealdah': 'sealdah',
  'sealdha': 'sealdah',
  'kalighat': 'kalighat',
  'chetla': 'chetla',
  'chowrasta': 'behala-chowrasta',
  'behala chowrastha': 'behala-chowrasta',
  'behala chorasta': 'behala-chowrasta',
  'behala tram depot': 'behala-tram-depot',
  'taratala xing': 'taratala-xing',
  'taratala more': 'taratala-xing',
  'bbd bag': 'bbd-bag',
  'dalhousie': 'bbd-bag',
  'bbd bag/gpo': 'bbd-bag',
  'mission row xing/bbd bag': 'bbd-bag',
  'chiria more': 'chiria-more',
  'barabazar': 'burrabazar',
  'barrabazar': 'burrabazar',
  'garia': 'garia',
  'jadavpur': 'jadavpur',
  'jadavpore': 'jadavpur',
  'dhakuria': 'dhakuria',
  'golpark': 'golpark',
  'r.b. ave': 'rashbehari',
  'rb ave': 'rashbehari',
  'rashbehari xing': 'rashbehari',
  'rashbihari': 'rashbehari',
  'rb av xing': 'rashbehari',
  'exide': 'rabindra-sadan',
  'rabindra sadan': 'rabindra-sadan',
  'rabindrasadan': 'rabindra-sadan',
  'hridaypur': 'hridaypur',
  'madhyamgram chowrasta': 'madhyamgram',
  'madhyamgram': 'madhyamgram',
  'doltala': 'doltala',
  'birati more': 'birati',
  'birati': 'birati',
  'airport gate no. 1': 'airport-gate-1',
  'airport': 'airport-gate-1',
  'airport 1 no. gate': 'airport-gate-1',
  'airport 1no': 'airport-gate-1',
  'kaikhali/haldiram': 'kaikhali',
  'kaikhali': 'kaikhali',
  'kestopur/baguihati': 'baguiati',
  'baguiati': 'baguiati',
  'kestopur': 'kestopur',
  'lake town xing': 'lake-town',
  'laketown': 'lake-town',
  'kankurgachi': 'kankurgachi',
  'girish park': 'girish-park',
  'm.g. road xing': 'mg-road',
  'm.g. road': 'mg-road',
  'm.g. road jn': 'mg-road',
  'hastings': 'water-gate',
  'water gate': 'water-gate',
  'thakurpukur': 'thakurpukur',
  'thakurpukur 3a stand': 'thakurpukur',
  'thakurpukur 3a bus stand': 'thakurpukur',
  'thakurpukur bazar': 'thakurpukur',
  'cancer hospital': 'cancer-hospital',
  'kabardanga': 'kabardanga',
  'haridevpur': 'haridevpur',
  'karunamoyee (tollygunge)': 'tollygunge-karunamoyee',
  'tollygunge metro': 'tollygunge',
  'tollygunge': 'tollygunge',
  'tollygunge tram depot': 'tollygunge',
  'tollygunge phari': 'tollygunge-phari',
  'gariahat': 'gariahat',
  'gariahgat': 'gariahat',
  'ruby': 'ruby',
  'ruby hospital': 'ruby',
  'rubi hospital': 'ruby',
  'chingrihata': 'chingrighata',
  'chingrighata': 'chingrighata',
  'chinghreeghata': 'chingrighata',
  'chinrighata': 'chingrighata',
  'sdf': 'sdf-building',
  'sec5': 'salt-lake-sector-v',
  'college more': 'college-more',
  'technopolis': 'technopolis',
  'techopolis': 'technopolis',
  'ajoynagar': 'ajoy-nagar',
  'ajay nagar': 'ajoy-nagar',
  'ajaynagar': 'ajoy-nagar',
  'central park': 'central-park',
  'narkel bagan': 'narkelbagan',
  'narkelbagan': 'narkelbagan',
  'narkelbagn': 'narkelbagan',
  'newtown': 'new-town-bus-stand',
  'new town': 'new-town-bus-stand',
  'science city': 'science-city',
  'since city': 'science-city',
  'topsia': 'topsia',
  'topsia more': 'topsia',
  'patuli': 'patuli',
  'patuli more': 'patuli',
  'peerless hospital': 'peerless-hospital',
  'peerless': 'peerless-hospital',
  'metropolitan': 'metropolitan',
  'metropolitan hou. est.': 'metropolitan',
  'kbkc more': 'kbkc-more',
  'kalikapur': 'kalikapur-em-bypass',
  'james long sarani': 'james-long-sarani',
  'v.i.p. road': 'vip-road',
  'babughat': 'babughat',
  'princep ghat': 'princep-ghat',
  'hiland park': 'hiland-park',
  'em bypass': 'em-bypass-connector',
  'em byapss': 'em-bypass-connector',
  'em bypass connector': 'em-bypass-connector',
  'vip bazar': 'vip-bazar',
  'vip nagar': 'vip-bazar',
  'cit road': 'cit-road',
  'dunlop more': 'dunlop',
  'bonhooghly': 'bonhooghly',
  'sinthee more': 'sinthi-more',
  'sovabazar': 'shovabazar-sutanuti',
  'sakher bazar': 'sakherbazar',
  'sakhar bazar': 'sakherbazar',
  'behala': 'behala',
  'majherhat': 'majherhat',
  'rajabazar': 'rajabazar',
  'bowbazar': 'bb-ganguly-street',
  'central avenue': 'cr-avenue',
  'barasat': 'barasat',
  'eco park': 'eco-park',
  'ecospace': 'eco-space',
  'eco space': 'eco-space',
  'aliah university': 'aliah-university',
  'minto park': 'minto-park',
  'park circus': 'park-circus-tram-depot',
  'new alipore': 'new-alipore',
  'sukanta nagar': 'sukanta-nagar',
  'nicco park': 'nicco-park',
  'home town': 'home-town',
  'vivekananda rd': 'vivekananda-road',
  'bb ganguly xing': 'bb-ganguly-street',
  'bb ganguly st': 'bb-ganguly-street',
  'pnb': 'pnb-more',
  'labony': 'salt-lake-laboni',
  'karunamoyee': 'karunamoyee',
  'dakshineswar': 'dakshineswar',
  'dum dum stn': 'dum-dum-station',
  'kudghat': 'kudghat',
  'nabanna': 'nabanna',
  'kasba ps': 'kasba',
  'b.t. college': 'bt-college',
  'bt college': 'bt-college',
  'new barrackpur b.t. college': 'bt-college',
  'kamalgazi': 'kamalgazi',
  'kamalgazi more': 'kamalgazi',
  'dhalai bridge': 'dhalai-bridge',
  'phoolbagan': 'phoolbagan',
};

const unmatched = new Set<string>();
const matched = new Map<string, string>();

for (const r of routesRaw) {
  for (const stopRaw of r.stops) {
    const key = stopRaw.toLowerCase().trim();
    if (ALIASES[key]) {
      matched.set(stopRaw, ALIASES[key]);
    } else if (stopNameMap.has(key)) {
      matched.set(stopRaw, stopNameMap.get(key)!);
    } else {
      unmatched.add(stopRaw);
    }
  }
}

console.log("Matched raw names:", matched.size);
console.log("Unmatched raw names:", unmatched.size);
console.log("\nList of unmatched stops:");
console.log(Array.from(unmatched).sort());
