import { STOPS } from './src/data/transitData';
import fs from 'fs';

// All raw stop names from parse_routes.ts
import './parse_routes';

// Let's create an alias map
const ALIAS_MAP: Record<string, string> = {
  // Existing stops mappings
  'khidderpur': 'khidderpur',
  'khidirpur': 'khidderpur',
  'khiddirpur': 'khidderpur',
  'khidderpore': 'khidderpur',
  'khiddirpor': 'khidderpur',
  'mominpur': 'mominpur',
  'mominpore': 'mominpur',
  'hazra': 'hazra-road',
  'hazra rd': 'hazra-road',
  'hazra road': 'hazra-road',
  'hazra park': 'hazra-road',
  'elgin': 'elgin-road',
  'elgin rd': 'elgin-road',
  'elgin road': 'elgin-road',
  'park street': 'park-street',
  'park st': 'park-street',
  'parkstreet': 'park-street',
  'esplanade': 'esplanade',
  'espl': 'esplanade',
  'moulali': 'moulali',
  'moulali more': 'moulali',
  'ultadanga': 'ultadanga',
  'hudco': 'ultadanga',
  'hudco/ultadanga': 'ultadanga',
  'khanna': 'khanna',
  'howrah bridge east': 'howrah-bridge',
  'howrah bridge south': 'howrah-bridge',
  'howrah bridge': 'howrah-bridge',
  'howrah stn': 'howrah-station',
  'howrah station': 'howrah-station',
  'howrah': 'howrah-station',
  'shyambazar': 'shyambazar',
  'shyam bazar': 'shyambazar',
  'manicktala': 'maniktala',
  'maniktala': 'maniktala',
  'sealdah': 'sealdah',
  'sealdha': 'sealdah',
  'kalighat': 'kalighat',
  'chetla': 'chetla',
  'chowrasta': 'behala-chowrasta',
  'behala chowrastha': 'behala-chowrasta',
  'behala chorasta': 'behala-chowrasta',
  'behala tram depot': 'behala-tram-depot',
  'taratala xing': 'taratala-xing',
  'taratala more': 'taratala-xing',
  'bbd bag': 'bbd-bag',
  'dalhousie': 'bbd-bag',
  'bbd bag/gpo': 'bbd-bag',
  'mission row xing/bbd bag': 'bbd-bag',
  'chiria more': 'chiria-more',
  'barabazar': 'burrabazar',
  'barrabazar': 'burrabazar',
  'garia': 'garia',
  'jadavpur': 'jadavpur',
  'jadavpore': 'jadavpur',
  'dhakuria': 'dhakuria',
  'golpark': 'golpark',
  'r.b. ave': 'rashbehari',
  'rb ave': 'rashbehari',
  'rashbehari xing': 'rashbehari',
  'rashbihari': 'rashbehari',
  'rb av xing': 'rashbehari',
  'exide': 'rabindra-sadan',
  'rabindra sadan': 'rabindra-sadan',
  'rabindrasadan': 'rabindra-sadan',
  'hridaypur': 'hridaypur',
  'madhyamgram chowrasta': 'madhyamgram',
  'madhyamgram': 'madhyamgram',
  'doltala': 'doltala',
  'birati more': 'birati',
  'birati': 'birati',
  'airport gate no. 1': 'airport-gate-1',
  'airport': 'airport-gate-1',
  'airport 1 no. gate': 'airport-gate-1',
  'airport 1no': 'airport-gate-1',
  'kaikhali/haldiram': 'kaikhali',
  'kaikhali': 'kaikhali',
  'kestopur/baguihati': 'baguiati',
  'baguiati': 'baguiati',
  'kestopur': 'kestopur',
  'lake town xing': 'lake-town',
  'laketown': 'lake-town',
  'kankurgachi': 'kankurgachi',
  'girish park': 'girish-park',
  'm.g. road xing': 'mg-road',
  'm.g. road': 'mg-road',
  'm.g. road jn': 'mg-road',
  'hastings': 'water-gate',
  'water gate': 'water-gate',
  'thakurpukur': 'thakurpukur',
  'thakurpukur 3a stand': 'thakurpukur',
  'thakurpukur 3a bus stand': 'thakurpukur',
  'thakurpukur bazar': 'thakurpukur',
  'cancer hospital': 'cancer-hospital',
  'kabardanga': 'kabardanga',
  'haridevpur': 'haridevpur',
  'karunamoyee (tollygunge)': 'tollygunge-karunamoyee',
  'tollygunge metro': 'tollygunge',
  'tollygunge': 'tollygunge',
  'tollygunge tram depot': 'tollygunge',
  'tollygunge phari': 'tollygunge-phari',
  'gariahat': 'gariahat',
  'gariahgat': 'gariahat',
  'ruby': 'ruby',
  'ruby hospital': 'ruby',
  'rubi hospital': 'ruby',
  'chingrihata': 'chingrighata',
  'chingrighata': 'chingrighata',
  'chinghreeghata': 'chingrighata',
  'chinrighata': 'chingrighata',
  'sdf': 'sdf-building',
  'sec5': 'salt-lake-sector-v',
  'college more': 'college-more',
  'technopolis': 'technopolis',
  'techopolis': 'technopolis',
  'ajoynagar': 'ajoy-nagar',
  'ajay nagar': 'ajoy-nagar',
  'ajaynagar': 'ajoy-nagar',
  'central park': 'central-park',
  'narkel bagan': 'narkelbagan',
  'narkelbagan': 'narkelbagan',
  'narkelbagn': 'narkelbagan',
  'newtown': 'new-town-bus-stand',
  'new town': 'new-town-bus-stand',
  'science city': 'science-city',
  'since city': 'science-city',
  'topsia': 'topsia',
  'topsia more': 'topsia',
  'patuli': 'patuli',
  'patuli more': 'patuli',
  'peerless hospital': 'peerless-hospital',
  'peerless': 'peerless-hospital',
  'metropolitan': 'metropolitan',
  'metropolitan hou. est.': 'metropolitan',
  'kbkc more': 'kbkc-more',
  'kalikapur': 'kalikapur-em-bypass',
  'james long sarani': 'james-long-sarani',
  'v.i.p. road': 'vip-road',
  'babughat': 'babughat',
  'princep ghat': 'princep-ghat',
  'hiland park': 'hiland-park',
  'em bypass': 'em-bypass-connector',
  'em byapss': 'em-bypass-connector',
  'em bypass connector': 'em-bypass-connector',
  'vip bazar': 'vip-bazar',
  'vip nagar': 'vip-bazar',
  'cit road': 'cit-road',
  'dunlop more': 'dunlop',
  'bonhooghly': 'bonhooghly',
  'sinthee more': 'sinthi-more',
  'sovabazar': 'shovabazar-sutanuti',
  'sakher bazar': 'sakherbazar',
  'sakhar bazar': 'sakherbazar',
  'behala': 'behala',
  'majherhat': 'majherhat',
  'rajabazar': 'rajabazar',
  'bowbazar': 'bb-ganguly-street',
  'central avenue': 'cr-avenue',
  'barasat': 'barasat',
  'eco park': 'eco-park',
  'ecospace': 'eco-space',
  'eco space': 'eco-space',
  'aliah university': 'aliah-university',
  'minto park': 'minto-park',
  'park circus': 'park-circus-tram-depot',
  'new alipore': 'new-alipore',
  'sukanta nagar': 'sukanta-nagar',
  'nicco park': 'nicco-park',
  'home town': 'home-town',
  'vivekananda rd': 'vivekananda-road',
  'bb ganguly xing': 'bb-ganguly-street',
  'bb ganguly st': 'bb-ganguly-street',
  'pnb': 'pnb-more',
  'labony': 'salt-lake-laboni',
  'karunamoyee': 'karunamoyee',
  'dakshineswar': 'dakshineswar',
  'dum dum stn': 'dum-dum-station',
  'kudghat': 'kudghat',
  'nabanna': 'nabanna',
};

// Check which raw names in routesRaw are matched
const existingStopIds = new Set(STOPS.map(s => s.id));
const existingStopNames = new Map(STOPS.map(s => [s.name.toLowerCase(), s.id]));

console.log("Existing stop IDs count:", existingStopIds.size);
